/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UploadTranscript': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'discovery.analyze'; data: never }>
    'TaskBreakdownTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'task.breakdown'; data: never }>
    'SpecTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'spec.generate'; data: never }>
    'PRDTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'prd.generate'; data: never }>
    'MockTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'feature.visualize'; data: never }>
    'GitHubPush': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown>, never>
    'CanvasUpdate': EventHandler<never, never>
    'AuditTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<402, unknown>, { topic: 'redhat.audit'; data: never }>
    'AskTrigger': ApiRouteHandler<unknown, ApiResponse<200, unknown>, { topic: 'general.ask'; data: never }>
    'TaskAgent': EventHandler<never, { topic: 'canvas.update'; data: never }>
    'SpecAgent': EventHandler<never, { topic: 'canvas.update'; data: never }>
    'RedHatAuditAgent': EventHandler<never, { topic: 'canvas.update'; data: never }>
    'PRDAgent': EventHandler<never, { topic: 'canvas.update'; data: never }>
    'MockGenerator': EventHandler<never, { topic: 'canvas.update'; data: never }>
    'GeneralAgent': EventHandler<never, never>
    'DiscoveryAgent': EventHandler<never, { topic: 'canvas.update'; data: never }>
  }
    
}